---
# Ansible playbook for provision LAMP stack (Linux, Apache, MySQL, PHP)
# @author Kiet Lam (2015)

- hosts: lamp
  sudo: true

  vars_files:
    - vars/main.yml

  pre_tasks:
    #- name: update apt cache
    #  apt: update_cache=yes

  roles:
    - webserver
    - database
